/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_school_calc_CppLib */

#ifndef _Included_edu_school_calc_CppLib
#define _Included_edu_school_calc_CppLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_school_calc_CppLib
 * Method:    getComputeResult
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_school_calc_CppLib_getComputeResult
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     edu_school_calc_CppLib
 * Method:    isValidExpression
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jboolean JNICALL Java_edu_school_calc_CppLib_isValidExpression
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
